### ISSUE TITLE
Deprecation Warning When Using Eslint v5.x

### ISSUE THREAD

**Issue by ryanwiemer** [brandonkal/eslint-config-gatsby-standard#1]
## Warning message shown when using eslint v5.x
```
node:1449) [ESLINT_LEGACY_OBJECT_REST_SPREAD] DeprecationWarning: The 'parserOptions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated. Use 'parserOptions.ecmaVersion' instead. (found in "standard-react")
(node:1449) [ESLINT_LEGACY_OBJECT_REST_SPREAD] DeprecationWarning: The 'parserOptions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated. Use 'parserOptions.ecmaVersion' instead. (found in "node_modules/eslint-config-standard-jsx/index.js")
(node:1449) [ESLINT_LEGACY_OBJECT_REST_SPREAD] DeprecationWarning: The 'parserOptions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated. Use 'parserOptions.ecmaVersion' instead. (found in "standard")
```

## Issues related to this topic
- https://github.com/ryanwiemer/gatsby-starter-gcn/issues/31
- https://github.com/airbnb/javascript/issues/1845
- https://github.com/airbnb/javascript/issues/1834

I haven't looked into this too much since it is only a deprecation warning but you may want to research what changes are needed to make this repo fully compatible with eslint `v5.x`. In the meantime I will keep using eslint `v4.x`

**Comment by brandonkal** [comment]
Thank you. I am still waiting for some dependencies to support eslint v5.x in order update. I made a note of it here: https://github.com/ryanwiemer/gatsby-starter-gcn/commit/dac64f52b65e3409cead7e7abc9dc5b7e34ef888

**Comment by ryanwiemer** [comment]
Cool. Sounds good.

**Comment by brandonkal** [comment]
v2 has been released with the updates required to support eslint v5.5.0. I have also made a pull request to your v2 branch. Thank you for the report.
